sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

sylius_admin_product:
    resource: "@SyliusAdminBundle/Resources/config/routing/product.yml"

#
#sylius_admin_product:
#    resource: |
#        alias: sylius.product
#        section: admin
#        templates: "@SyliusAdmin\\Crud"
#        except: ['index', 'update']
#        redirect: update
#        grid: sylius_admin_product
#        permission: true
#        vars:
#            all:
#                subheader: sylius.ui.manage_your_product_catalog
#                templates:
#                    form: "@SyliusAdmin/Product/_form.html.twig"
#            index:
#                icon: cube
#    type: sylius.resource

#sylius_admin_product_index:
#    path: /products/
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.product:indexAction
#        _sylius:
#            section: admin
#            permission: true
#            grid: sylius_admin_product
#            template: "@SyliusAdmin/Product/index.html.twig"
#            vars:
#                subheader: sylius.ui.manage_your_product_catalog
#                icon: cube


sylius_admin_product_update:
    path: /products/{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: App\Controller\CustomEditProduct::updateAction
        _sylius:
            section: admin
            permission: true
            redirect: referer
            template: "@SyliusAdmin/Crud/update.html.twig"
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
                templates:
                    form: "@SyliusAdmin/Product/_form.html.twig"
                    toolbar: "@SyliusAdmin/Product/Update/_toolbar.html.twig"

